; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; CellOS LV2 is 64-bit PowerPC (ELFv1, 64-bit GPRs) with 32-bit pointers.
; Pointers are 64-bit (zero-extended) in registers and 32-bit in memory.
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-unknown-lv2 < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -O0 -mtriple=powerpc64-unknown-lv2 < %s | FileCheck %s --check-prefix=O0
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-unknown-lv2 -filetype=obj < %s | \
; RUN:   llvm-readobj -r - | FileCheck %s --check-prefix=RELOC

@g = external constant [7 x i8]
@gp = global ptr @g

; RELOC:      Section ({{[0-9]+}}) .rela.data {
; RELOC-NEXT:   0x0 R_PPC64_ADDR32 g 0x0
; RELOC-NEXT: }
; RELOC:      Section ({{[0-9]+}}) .rela.toc {
; RELOC-NEXT:   0x0 R_PPC64_ADDR64 g 0x0
; RELOC-NEXT: }

define { ptr, i64 } @ret_global() {
; CHECK-LABEL: ret_global:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addis 3, 2, .LC0@toc@ha
; CHECK-NEXT:    li 4, 6
; CHECK-NEXT:    ld 3, .LC0@toc@l(3)
; CHECK-NEXT:    blr
;
; O0-LABEL: ret_global:
; O0:       # %bb.0:
; O0-NEXT:    addis 3, 2, .LC0@toc@ha
; O0-NEXT:    ld 3, .LC0@toc@l(3)
; O0-NEXT:    li 4, 6
; O0-NEXT:    blr
  ret { ptr, i64 } { ptr @g, i64 6 }
}

define ptr @load_ptr(ptr %p) {
; CHECK-LABEL: load_ptr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lwz 3, 0(3)
; CHECK-NEXT:    blr
;
; O0-LABEL: load_ptr:
; O0:       # %bb.0:
; O0-NEXT:    lwz 3, 0(3)
; O0-NEXT:    blr
  %v = load ptr, ptr %p
  ret ptr %v
}

define void @store_ptr(ptr %p, ptr %v) {
; CHECK-LABEL: store_ptr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stw 4, 0(3)
; CHECK-NEXT:    blr
;
; O0-LABEL: store_ptr:
; O0:       # %bb.0:
; O0-NEXT:    stw 4, 0(3)
; O0-NEXT:    blr
  store ptr %v, ptr %p
  ret void
}

define i32 @load_through_loaded_ptr(ptr %pp) {
; CHECK-LABEL: load_through_loaded_ptr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lwz 3, 0(3)
; CHECK-NEXT:    lwz 3, 0(3)
; CHECK-NEXT:    blr
;
; O0-LABEL: load_through_loaded_ptr:
; O0:       # %bb.0:
; O0-NEXT:    lwz 3, 0(3)
; O0-NEXT:    lwz 3, 0(3)
; O0-NEXT:    blr
  %p = load ptr, ptr %pp
  %v = load i32, ptr %p
  ret i32 %v
}

; A GEP without inbounds may wrap the 32-bit address space.
define ptr @gep_wrap(ptr %p, i32 %i) {
; CHECK-LABEL: gep_wrap:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sldi 4, 4, 2
; CHECK-NEXT:    add 3, 3, 4
; CHECK-NEXT:    clrldi 3, 3, 32
; CHECK-NEXT:    blr
;
; O0-LABEL: gep_wrap:
; O0:       # %bb.0:
; O0-NEXT:    sldi 4, 4, 2
; O0-NEXT:    add 3, 3, 4
; O0-NEXT:    clrldi 3, 3, 32
; O0-NEXT:    blr
  %q = getelementptr i32, ptr %p, i32 %i
  ret ptr %q
}

define ptr @gep_inbounds(ptr %p, i32 %i) {
; CHECK-LABEL: gep_inbounds:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extsw 4, 4
; CHECK-NEXT:    sldi 4, 4, 2
; CHECK-NEXT:    add 3, 3, 4
; CHECK-NEXT:    blr
;
; O0-LABEL: gep_inbounds:
; O0:       # %bb.0:
; O0-NEXT:    extsw 4, 4
; O0-NEXT:    sldi 4, 4, 2
; O0-NEXT:    add 3, 3, 4
; O0-NEXT:    blr
  %q = getelementptr inbounds i32, ptr %p, i32 %i
  ret ptr %q
}

define ptr @int_to_ptr(i32 %i) {
; CHECK-LABEL: int_to_ptr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    clrldi 3, 3, 32
; CHECK-NEXT:    blr
;
; O0-LABEL: int_to_ptr:
; O0:       # %bb.0:
; O0-NEXT:    clrldi 3, 3, 32
; O0-NEXT:    blr
  %p = inttoptr i32 %i to ptr
  ret ptr %p
}

; va_list is a single 4-byte pointer into the doubleword-slotted parameter
; save area.
define ptr @vararg(i32 %n, ...) {
; CHECK-LABEL: vararg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mflr 0
; CHECK-NEXT:    stdu 1, -144(1)
; CHECK-NEXT:    std 0, 160(1)
; CHECK-NEXT:    .cfi_def_cfa_offset 144
; CHECK-NEXT:    .cfi_offset lr, 16
; CHECK-NEXT:    .cfi_offset r30, -16
; CHECK-NEXT:    addi 3, 1, 208
; CHECK-NEXT:    std 4, 200(1)
; CHECK-NEXT:    addi 4, 1, 200
; CHECK-NEXT:    rlwinm 4, 4, 0, 0, 28
; CHECK-NEXT:    std 30, 128(1) # 8-byte Folded Spill
; CHECK-NEXT:    std 5, 208(1)
; CHECK-NEXT:    std 6, 216(1)
; CHECK-NEXT:    std 7, 224(1)
; CHECK-NEXT:    std 8, 232(1)
; CHECK-NEXT:    std 9, 240(1)
; CHECK-NEXT:    std 10, 248(1)
; CHECK-NEXT:    stw 3, 124(1)
; CHECK-NEXT:    rlwinm 3, 3, 0, 0, 28
; CHECK-NEXT:    lwz 30, 4(4)
; CHECK-NEXT:    addi 4, 1, 216
; CHECK-NEXT:    stw 4, 124(1)
; CHECK-NEXT:    ld 4, 0(3)
; CHECK-NEXT:    lwz 3, 124(1)
; CHECK-NEXT:    stw 3, 120(1)
; CHECK-NEXT:    addi 3, 1, 120
; CHECK-NEXT:    bl use
; CHECK-NEXT:    nop
; CHECK-NEXT:    mr 3, 30
; CHECK-NEXT:    ld 30, 128(1) # 8-byte Folded Reload
; CHECK-NEXT:    addi 1, 1, 144
; CHECK-NEXT:    ld 0, 16(1)
; CHECK-NEXT:    mtlr 0
; CHECK-NEXT:    blr
;
; O0-LABEL: vararg:
; O0:       # %bb.0:
; O0-NEXT:    mflr 0
; O0-NEXT:    stdu 1, -128(1)
; O0-NEXT:    std 0, 144(1)
; O0-NEXT:    .cfi_def_cfa_offset 128
; O0-NEXT:    .cfi_offset lr, 16
; O0-NEXT:    std 10, 232(1)
; O0-NEXT:    std 9, 224(1)
; O0-NEXT:    std 8, 216(1)
; O0-NEXT:    std 7, 208(1)
; O0-NEXT:    std 6, 200(1)
; O0-NEXT:    std 5, 192(1)
; O0-NEXT:    std 4, 184(1)
; O0-NEXT:    addi 3, 1, 184
; O0-NEXT:    stw 3, 124(1)
; O0-NEXT:    lwz 3, 124(1)
; O0-NEXT:    addi 4, 3, 8
; O0-NEXT:    stw 4, 124(1)
; O0-NEXT:    lwz 3, 4(3)
; O0-NEXT:    std 3, 112(1) # 8-byte Folded Spill
; O0-NEXT:    lwz 3, 124(1)
; O0-NEXT:    addi 4, 3, 8
; O0-NEXT:    stw 4, 124(1)
; O0-NEXT:    ld 4, 0(3)
; O0-NEXT:    lwz 3, 124(1)
; O0-NEXT:    stw 3, 120(1)
; O0-NEXT:    addi 3, 1, 120
; O0-NEXT:    bl use
; O0-NEXT:    nop
; O0-NEXT:    ld 3, 112(1) # 8-byte Folded Reload
; O0-NEXT:    addi 1, 1, 128
; O0-NEXT:    ld 0, 16(1)
; O0-NEXT:    mtlr 0
; O0-NEXT:    blr
  %ap = alloca ptr
  %ap2 = alloca ptr
  call void @llvm.va_start(ptr %ap)
  %a = va_arg ptr %ap, ptr
  %b = va_arg ptr %ap, i64
  call void @llvm.va_copy(ptr %ap2, ptr %ap)
  call void @use(ptr %ap2, i64 %b)
  call void @llvm.va_end(ptr %ap)
  ret ptr %a
}

declare void @use(ptr, i64)
